### ISSUE TITLE
我现在运用你这个开源代码写了一个播放器，如何设置才能不被其他播放器强制关闭？

### ISSUE THREAD

**Issue by guokai1120** [douban/DOUAudioStreamer#106]
现在我写的播放器，只要是其他的播放器打开就会将我的播放器强制关闭？

**Comment by lembacon** [comment]
如果有 foreground application 将其 audio session 的 category 设为 media playback 且将 audio session 设置为 active，那么就会发生你所说的情况。

理论上，application 应该在开始播放的时候才应该将 audio session 置为 active，但是如果他们在 application 进入前台就这么干，那其实是无能为力的。
