### ISSUE TITLE
程序进入后台播放没有问题，但是锁屏8-10秒之后必定崩溃

### ISSUE THREAD

**Issue by tsm-soloc** [douban/DOUAudioStreamer#111]
程序进入后台播放没有问题，但是锁屏8-10秒之后必定崩溃
在playbackitem.m

static OSStatus audio_file_read(void *inClientData,
                                SInt64 inPosition,
                                UInt32 requestCount,
                                void *buffer, 
                                UInt32 *actualCount)
{
  __unsafe_unretained DOUAudioPlaybackItem *item = (__bridge DOUAudioPlaybackItem *)inClientData;

  if (inPosition + requestCount > [[item mappedData] length]) {
    if (inPosition >= [[item mappedData] length]) {
      *actualCount = 0;
    }
    else {
      *actualCount = (UInt32)((SInt64)[[item mappedData] length] - inPosition);
    }
  }
  else {
    *actualCount = requestCount;
  }

  if (*actualCount == 0) {
    return noErr;
  }

  if ([item filePreprocessor] == nil)
  {
    memcpy(buffer, (uint8_t *)[[item mappedData] bytes] + inPosition, *actualCount);
  }
  else {
    NSData *input = [NSData dataWithBytesNoCopy:(uint8_t *)[[item mappedData] bytes] + inPosition
                                         length:*actualCount
                                   freeWhenDone:NO];
    NSData *output = [[item filePreprocessor] handleData:input offset:(NSUInteger)inPosition];
    memcpy(buffer, [output bytes], [output length]);
  }

  return noErr;
}

在memcpy(buffer, (uint8_t *)[[item mappedData] bytes] + inPosition, *actualCount);中直接崩溃。。

**Comment by lembacon** [comment]
是不是开了 Data Protection 了？

**Comment by tsm-soloc** [comment]
没有。。。

**Comment by tsm-soloc** [comment]
谢谢，已经解决了，  确实是Data Protection的问题，但是我证书并没有打开Data Protection权限，我把Data Protection权限打开更新证书，再关闭更新证书就OK了。。。 多谢。。。
