### ISSUE TITLE
编译OS X 10.10 编译错误

### ISSUE THREAD

**Issue by dadameng** [douban/DOUAudioStreamer#116]
项目里Cocopods里面只有AFN  项目的target空的工程 然后编译报错  编译OS X版本

Undefined symbols for architecture x86_64:
  "_AudioSessionSetActive", referenced from:
      -[DOUAudioEventLoop _handleEvent:withStreamer:] in libDOUAudioStreamer.a(DOUAudioEventLoop.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lembacon** [comment]
0.2.11 的时候弄坏的，但是 0.2.14 已经修好了。更新一下吧。

**Comment by dadameng** [comment]
thanks   我的还真是 0.2.11
