### ISSUE TITLE
没有找到如何 seek 到指定的时间位置

### ISSUE THREAD

**Issue by sunyazhou13** [douban/DOUAudioStreamer#117]
没找到哪能 seekToTime 的类似方法 能让播放音乐的过程中 滑动 滑块到指定的时间位置 来保证 音乐还在持续播放的 api

目前来看 滑动的过程中 音乐貌似跟随滑动这个声音不是特别好
有点类似 
AudioFileStreamSeek() 的函数

**Comment by lembacon** [comment]
`-[DOUAudioStreamer setCurrentTime:]`

https://github.com/douban/DOUAudioStreamer/blob/master/src/DOUAudioStreamer.h#L59

**Comment by sunyazhou13** [comment]
这个是直接切换到指定的位置，但是如果是滑块滑动过程中要保证音乐还处于播放状态而不是破坏音乐轨道那种

**Comment by lembacon** [comment]
两种选项：

1. 直接调用一次 `-[DOUAudioStreamer setCurrentTime:]` 设置到目标时间位置；
2. 滑动过程中，持续调用 `-[DOUAudioStreamer setCurrentTime:]`。

**Comment by sunyazhou13** [comment]
如果不想持续调用的话 那控制滑块进度条的逻辑就在上层了，那也只能这样了 谢谢

**Comment by syxiaqj** [comment]
DOUAudioStreamer的实例调用currentTime时，什么情况下才会有效，在play方法后，立马调用currentTime，并非每次均有效，为什么？
