### ISSUE TITLE
网络播放aac格式的音频会提前结束

### ISSUE THREAD

**Issue by wlgemini** [douban/DOUAudioStreamer#130]
我在iOS端录制的aac格式的音频上传给服务器，但在线播放时会提前结束，我猜测是播放进度追上缓存进度时，就会结束。通过测试，发现跟我录音时用的配置有关，因为其他的AAC资源是能够正常播放的，我不知如何修正这些配置。以下是我录音的配置：
    [dicM setObject:@(kAudioFormatMPEG4AAC) forKey:AVFormatIDKey];
    [dicM setObject:@44100 forKey:AVSampleRateKey];
    [dicM setObject:@1 forKey:AVNumberOfChannelsKey];
    [dicM setObject:@8 forKey:AVLinearPCMBitDepthKey];
    [dicM setObject:@(AVAudioQualityHigh) forKey:AVEncoderAudioQualityKey];

**Comment by ongtzewei** [comment]
@wlgemini 你最终有找到解决方案吗？
