### ISSUE TITLE
Android设备录制的.aac格式音频有问题

### ISSUE THREAD

**Issue by faxianlei** [douban/DOUAudioStreamer#154]
1、在播放时不能拿到`DOUAudioStreamer`正确的`duration`；
2、在播放一段后停止（并未播放完），应该也是`duration的`问题；
以上问题，不知道是不是我的使用姿势有问题，还是其他的问题；
附播放链接 https://oimryzjfe.qnssl.com/content/b5026357e257473cb570fb19567e074f.aac
谢谢！

**Comment by QiuZhiFei** [comment]
![image](https://user-images.githubusercontent.com/3402799/31488847-a02007fa-af04-11e7-8a73-c75fe7999ffb.png)

**Comment by likegoto** [comment]
谢谢
