### ISSUE TITLE
AUIOClient_StartIO failed (560557684)

### ISSUE THREAD

**Issue by danylokos** [douban/DOUAudioStreamer#17]
Hi, want to say thanks for this great project, hope it will continue growing! 
It works well, but found one annoying bug: 
when DOUAudioStreamer object starts playing track and at the same moment you receive a call, or start another music application and play audio, it will log an error: "ERROR:     [com.douban.audio-streamer.event-loop] 1207: AUIOClient_StartIO failed (560557684)" and will enter to undefined state, it will not respond to any action: play,pause, stop or reset.

**Comment by Aufree** [comment]
Hi, @lembacon I got the same problem when DOUAudioStreamer object starts playing track and at the same moment I start another application(like wechat) and play audio, it will log an error: `[com.douban.audio-streamer.event-loop] 1232: AUIOClient_StartIO failed (560557684)`

**Comment by zhangyqyx** [comment]
请问一下 [aurioc] 1316: AUIOClient_StartIO failed (561015905) 这个是什么错误呀？如何解决呢？
