### ISSUE TITLE
Option to play local audio files

### ISSUE THREAD

**Issue by lukaswelte** [douban/DOUAudioStreamer#19]
It would be great to have the option to pass a URL to a local file.
Writing apps supporting On and offline mode would be great this way.

**Comment by happy201993** [comment]
NSString *path = [NSString stringWithFormat:@"%@/1.mp3",NSHomeDirectory()];
      Track *track = [[Track alloc] init];
      [track setArtist:@"artist"];
      [track setTitle:@"title"];
      [track setAudioFileURL:[NSURL URLWithString:path]];
no way play local music file?

**Comment by paulief** [comment]
@lukaswelte I saw this was closed, was this ability added? It still doesn't seem to work.
