### ISSUE TITLE
 DOUAudioDecoder issue

### ISSUE THREAD

**Issue by chunyeah** [douban/DOUAudioStreamer#34]
Hi guys,

This method
- (DOUAudioDecoderStatus)decodeOnce
  in the DOUAudioDecoder.m

I found sometimes this method return DOUAudioDecoderEndEncountered, but the audio just buffer.

DOUAudioDecoder.m
Line 386: 
 if (ioOutputDataPackets == 0) {
    [_lpcm setEnd:YES];
    pthread_mutex_unlock(&_decodingContext.mutex);
    return DOUAudioDecoderEndEncountered;
  }

Why the ioOutputDataPackets == 0, but audio just buffer?

Thank you.

**Comment by iDevelopper** [comment]
@once2go , did you find the solution?
