### ISSUE TITLE
能否使用DouAudioStreamer播放AAC格式的音频数据

### ISSUE THREAD

**Issue by TimeKillerA** [douban/DOUAudioStreamer#56]
目前在做一个视频播放器，音频部分是AAC格式的数据，想请问一下是否可以使用DouAudioStreamer来播放NSData,而不是播放一个音频文件，如果可以的话，麻烦告知一下方法，不胜感激！

**Comment by lembacon** [comment]
那样的话，其实并没有使用 DOUAudioStreamer 的必要了。直接用 AVPlayer 就可以了。
