### ISSUE TITLE
音频解码失败的错误

### ISSUE THREAD

**Issue by yushuyi** [douban/DOUAudioStreamer#6]
从百度分享那里取来的下载链接,如下:
http://pan.baidu.com/share/link?shareid=533818&uk=2032859066

然后右键拷贝出来具体文件的下载地址.就像这样的地址:

http://d.pcs.baidu.com/file/2d9cad8a977bdd5ffc05282aa9ca3cce?fid=2032859066-250528-2190128000&time=1369982858&sign=FDTAR-DCb740ccc5511e5e8fedcff06b081203-L0%2F3dQiS2BDMaH%2BglFbDqrj1AcQ%3D&rt=sh&expires=8h&r=811992230&sh=1&response-cache-control=private

但是通过DOUAudioStreamer 读取 会报解码错误. 无法播放 

但是后台依旧正在在下载这个文件. 

或者像这样的音频下载地址:
http://files.parse.com/2d7cec80-f800-4a36-82dd-d9a9fc59084e/366ba502-1328-4f5c-9360-5934f2312728-file

有时候成功,有时候失败,这是为什么....

**Comment by snowCoveredPoetry** [comment]
请教一下 你的问题 解决了吗  @yushuyi
