### ISSUE TITLE
kevent可能失效的问题

### ISSUE THREAD

**Issue by matthewyan** [douban/DOUAudioStreamer#60]
在其它App播放音乐时，我自己的播放app需要暂停，但发现调用pause后，走到:
- (void)_sendEvent:(event_type)event userData:(void *)userData
里面，kevent触发

但在_waitForEventWithTimeout里面没有收到相应事件
int n = kevent(_kq, NULL, 0, &kev, 1, ts);

这个直接就停这了，没有事件触发了，导致拋过来的pause事件没有被处理
不知道这个是需要怎么处理？ 谢谢

**Comment by lembacon** [comment]
看起来应该是 App 进入后台了，这边需要你自己相应的去调用 `-beginBackgroundTaskWithExpirationHandler:` 以及 `-endBackgroundTask:`。

**Comment by mayu0418** [comment]
@lembacon   遇到了相同问题 请教下怎么解决
