### ISSUE TITLE
使用的时候发现两个问题

### ISSUE THREAD

**Issue by anpufeng** [douban/DOUAudioStreamer#61]
这个库很好, 使用起来也方便
但发现两个小问题
1:　在运行DEMO时切换到后台如果被铃声或电话等打断,在结束打断时调用AudioSessionSetActive(TRUE);STATUS返回状态码始终无法成功, 导致无法继续播放,这个问题纠结了好几天, 找了很多资料也没发现原因,后来无意中发现在切换DidEnterBackgroundNotification时必须调用
[[UIApplication sharedApplication] beginReceivingRemoteControlEvents]; 才不会出现重新激活AUDIOSESSION失败的问题
2:在ARM64下使用时发现无法输出SHA256, 跟踪时发现 if ([DOUAudioStreamer options] & DOUAudioStreamerRequireSHA256)没有进入 , 修改 
DOUAudioStreamerDefaultOptions = DOUAudioStreamerKeepPersistentVolume |
                                   DOUAudioStreamerRemoveCacheOnDeallocation |
                                    DOUAudioStreamerRequireSHA256
问题得到解决.

**Comment by johnlui** [comment]
你拯救了我，感谢 💯
